<table border="0" cellpadding="10">
    <tr>
      <td>
        <p align="left"><strong>Terms and Conditions</strong><br>
          <br>
          The use of this web site is subject to the Terms and Conditions set out below, which you should read carefully. By using this web site you agree to be legally bound by these Terms and Conditions. If you do not accept these Terms and Conditions, please discontinue and do not attempt to use this web site.</p>
        <p align="left">If you are under 18 years old, Please ask Mum or Dad to read these Terms and Conditions with you before using this web site.</p>
        <p align="left">You are wholly responsible for any use of this web site by any person or persons using your computers or directed by you and you must ensure that any such persons understands these terms.<br>
          <br>
          This web site and content is provided on an "as is" and "as available" basis and we give no warranty and make no representation regarding the accuracy, completeness or appropriateness of the content of this web site. You should obtain independent verification of any information on this web site before placing any reliance on it. Any information provided on this web site could be seasonal or out of date.</p>
        <p align="left">This web site is not intended to be used as a comprehensive and objective information resource. Consequently, we accept no liability for any losses or damages (whether direct, indirect, special, consequential or otherwise) arising out of content, content errors or omissions contained in this web site. Further, no representation or warranty is given that the web site shall be available on an uninterrupted basis, and no liability can be accepted in respect of losses or damages arising out of such unavailability or for any failure of performance, error, omission, interruption, defect, delay in operation or transmission or line or system failure. Also, we accept no liability in respect of losses or damages arising out of changes made to the content of this web site by authorized or unauthorized third parties, and we make no representation or warranty regarding the accuracy, functionality or performance of any third party software that may used in connection with this web site.</p>
        <p align="left">This is a private enterprise web site, There is a link to this Terms of use on our pages wherever we consider reasonable. If you are accessing chunks of or cache copies of any data that originates from this web site, be aware data may not be complete in our intent that it should always accompany easy reference to these Terms of use. We accept no liability on behalf of any third partys or third party mechanisms as this is outside our
          control. We recommend you also understand the terms of those other mechanisms and parties.<br>
          <br>
          We provide a platform of access to various content that is provided by other persons or corporations, as is their intent to give out to us or to you, in some or many cases their computers determine the type of content that they wish to provide by their automatic means. In visiting our website, and using our services you are causing their content to be fed to your web browser, you should be aware some content occasionally or often does not originate from us or our web site and we accept no liability for whatever content is delivered to you from other parties, your agents or those directed by you, from those third party agents weather via this service or indirectly via this service We also do not guarantee that or their content to be accurate, suitable, or appropriate. If you do not accept, please discontinue and do not attempt to use this web site.</p>
        <p align="left">Access to and use of this web site is at the user's sole risk and we do not warrant or imply that the use of this web site or any material viewed or downloaded from it will not cause loss or damage to any property or person or organization or business, including but not limited to loss of data or computer virus infection. Yours is your responsibility for adequate protection and back-up of data and/or equipment and to undertake reasonable and appropriate precautions to scan for computer viruses or for other destructive properties.</p>
        <p align="left">This web site may contain links to other web sites which are hosted and maintained by third parties. We have no control over the content or actions of any such site. You connect to such web sites at your own risk, and we make no representations and take no responsibility regarding the content or actions of any such web site. We shall not be liable for any loss or damage which may arise from the use that you make of any such third party web sites. Use of those web sites and any software downloaded from any such third party web site is governed by the terms of any license agreement which accompanies or is provided on the web site or with their software.<br>
          <br>
          By agreeing to be bound by these Terms and Conditions, you are agreeing that we may collect and store data about you as provided by you in accordance with our Privacy Policy.</p>
        <p align="left">In visiting our website, using our services, contacting us or having any dealings with us or our agents you agree we and our agents, accept no liability or responsibility on your behalf for any person, any device, any business, any organization or anything else.</p>
        <p align="left">In visiting our website, using our services, contacting us or having any dealings with us or our agents in any way, you agree that we reserve the rights to change, revise, backdate or update any or all of our
          Terms of use or other policy at any time. The contents of this web site, including these Terms and Conditions of use, may be subject to change update or backdate by us without notification. Where you continue to access,
          cache or record this web site and any data from this web site you agree to any and all changes.</p>
        <p align="left">You are visiting our web sites and servers "as is" with no implied warranty or liability.</p>
        <p align="left">In visiting our website, using our services, contacting us or having any dealings with us or our agents in any way, you agree to read, understand, and agree to, any and all of our terms of use and privacy policy which we reserve the right to revise</p>
        <p align="left">You agree that visiting our website, contacting us or having any dealings with us or anything that relates to us or our agents in any way is  at your and own  risk.</p>
        <p align="center">Having said all that, it is with our good intent, and any enquiry that we can assist you with  will try our best to answer or resolve or help you as soon as we can.</p>
        <p align="center"><strong>We are happy to help, please contact us<br><a href="http://4ustralia.com/#contact-us">HERE</a></strong></p>
        <p align="center"><img title="4ustralia.com" border="0" style="width:100%;max-width:321px" alt="4ustralia.com" src="/images/4ustralia.png" /><br />
          <font color="#FF0000"><strong>Community Portal Websites</strong></font> </p>
        <p align="center">&nbsp;</p></td>
    </tr>
</table>