<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentDetail extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'TOKEN', 'BILLINGAGREEMENTACCEPTEDSTATUS', 'CHECKOUTSTATUS', 'TIMESTAMP', 'CORRELATIONID', 'ACK', 'VERSION', 'BUILD', 'EMAIL',
		'PAYERID', 'PAYERSTATUS', 'FIRSTNAME', 'LASTNAME', 'COUNTRYCODE', 'ADDRESSSTATUS', 'CURRENCYCODE', 'AMT', 'ITEMAMT', 'SHIPPINGAMT', 'HANDLINGAMT', 'TAXAMT',
		'DESC', 'INVNUM', 'NOTIFYURL', 'INSURANCEAMT', 'SHIPDISCAMT', 'INSURANCEOPTIONOFFERED', 'L_NAME0', 'L_QTY0', 'L_TAXAMT0', 'L_AMT0', 'PAYMENTREQUEST_0_CURRENCYCODE', 'PAYMENTREQUEST_0_AMT',
		'PAYMENTREQUEST_0_ITEMAMT', 'PAYMENTREQUEST_0_SHIPPINGAMT', 'PAYMENTREQUEST_0_HANDLINGAMT', 'PAYMENTREQUEST_0_TAXAMT', 'PAYMENTREQUEST_0_DESC', 'PAYMENTREQUEST_0_INVNUM', 'PAYMENTREQUEST_0_NOTIFYURL',
		'PAYMENTREQUEST_0_INSURANCEAMT', 'PAYMENTREQUEST_0_SHIPDISCAMT', 'PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID', 'PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED', 'L_PAYMENTREQUEST_0_NAME0',
		'L_PAYMENTREQUEST_0_QTY0', 'L_PAYMENTREQUEST_0_TAXAMT0', 'L_PAYMENTREQUEST_0_AMT0', 'PAYMENTREQUESTINFO_0_ERRORCODE', 
		'customer_id', 'customer_level',  'period', 'date_paid', 'payment_status', 'date_cancelled',
    ];
}
